package MetaCrySL.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class AggregateList_Constraints extends BaseConstraintsDescriptor {
  public AggregateList_Constraints() {
    super(CONCEPTS.AggregateList$HE);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AggregateList$HE = MetaAdapterFactory.getConcept(0xfbc67e5cfd7043b1L, 0xb8373c3551c2500bL, 0x1df97434cb3fb78aL, "MetaCrySL.structure.AggregateList");
  }
}
