package MetaCrySL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a2a0a21b0nd = new IconResource("TextIcon_3.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a67b0nd = new IconResource("TextIcon_1.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a28b0nd = new IconResource("TextIcon_2.png", IconContainer.class);
}
